Translation
jhuapl-bio/pathogenesis-gene-ontology pull request #135
Opened 2020-10-30 13:06 UTC by awe220

Updates to the ontology for Issue #69, 68, 70, 71.

Determinant:
PATHGO:0000034, PATHGO:0000294, PATHGO:0000002, PATHGO:0000295, PATHGO:0000002, PATHGO:0000297, PATHGO:0000298

Mechanism:
PATHGO:0000006, PATHGO:00000299, PATHGO:0000025, PATHGO:0000244, PATHGO:0000265, PATHGO:0000266, PATHGO:0000267

2020-10-30 13:41 UTC, jacakrj1 commented
@aernlund Looks like Tina may be using ids 294-315 in PR #133.  Can you please review her commits and update the numbering of your terms to follow hers?

2020-11-02 22:19 UTC, jproesch requested changes
PATHGO_0000006  change label to "modulates protein synthesis"; definition should also be changed to match new label (definition still states "inhibition")

PATHGO_0000265 & PATHGO_0000299 replace "mediates modulation of" with "modulates" in labels and "mediating modulating of" with "modulating" in definitions

PATHGO_ 0000266, PATHGO_ 0000267,  PATHGO_0000244 & PATHGO_0000025:  replace "mediates modulation of" with "modulates" in definitions

Please also change numbers 294-299 to 316-320 & 323

2020-11-06 14:33 UTC, awe220 commented
Updated with new numbering (316-320, 323) and changed the wording for labels and definitions.

2020-11-06 16:19 UTC, jproesch approved these changes

2020-11-06 16:21 UTC, merged