Moving integrin binding term
jhuapl-bio/pathogenesis-gene-ontology pull request #207
Opened 2021-05-21 17:57 UTC by jacakrj1

Since integrin is a surface glycoprotein, it is a more specific example of cell surface glycoprotein binding

Addresses issue #179

2021-06-03 15:23 UTC, jproesch requested changes
need to modify definition

2021-06-03 15:34 UTC, genegodbold commented
Most cell surface proteins *are* glycoproteins so it wouldn't be out of place to have some children under it. 

I would not advise distinguishing them on the basis of the carbohydrate being O-linked (Ser/Thr) or N-linked (Asn)--I just don't know if that matters.

Other things on the cell surface that can serve as a docking place for adhesins are glycolipids.

2021-07-20 17:22 UTC, jproesch commented
@jacakrj1 can you address this? definition needs to be modified.  I believe you have to do it since I requested the change.

2021-07-22 06:05 UTC, jproesch commented
made this change in another pull request

2021-07-22 06:05 UTC, closed without merging